### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by komail2004** [joshuaDeal/chatGPT-cli#1]
prompt_toolkit is missing)*. It would be much more helpful if this library could be part of the uploaded file so user don't have to install it manually...

**Comment by joshuaDeal** [comment]
I think the best way to handle this would be to list it as a dependency in README.md. That way users whom don't already have it can download it the conventional way for their system.

**Comment by joshuaDeal** [comment]
8912b41.
I think the other libraries are generally already installed on most systems that run python so I haven't noted them in README.md
